import Head from 'next/head';
import { Card } from '../components/Card';
import styles from '../styles/Home.module.css';
import { DEFAULT_CARDS } from '../contants/defaultCards';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pomotimer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Pomo<span>Timer</span>
        </h2>
        <section className={styles.cards}>
          {DEFAULT_CARDS.map((card) => (
            <Card {...card} />
          ))}
        </section>
      </main>
    </div>
  );
}
