import Head from 'next/head';
import Image from 'next/image';
import { Card } from '../components/Card';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Pomo<span>Timer</span>
        </h2>
        <Card />
      </main>
    </div>
  );
}
