import { Timer } from '@components/Timer';
import { onCountdownDefault } from '@contants/defaultOnCountdown';
import { getColor } from '@utils/getColor';
import { getMinSecFormat, getTotalSec } from '@utils/TimeFormatConverter';
import gsap from 'gsap';
import Head from 'next/head';
import { useState, useEffect, useRef, useReducer} from 'react';
import { COUNTDOWN_ACTIONS, countdownReducer, COUNTDOWN_COUNTDOWN_ACTIONS } from 'reducer/countdownReducer';
import { Cards } from '../components/Cards';
import { Header } from '../components/Header';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [onCountdown, dispatch] = useReducer(countdownReducer, onCountdownDefault);

  const cardTime = {
    min: 2,
    sec: 1,
  };

  const [time, setTime] = useState(cardTime);

  const countdownAnimation = useRef();
  const countdownTime = {
    sec: getTotalSec(cardTime),
  };

  const handlerOnTimer = () => {
    if (onCountdown.status === null) {
      dispatch(COUNTDOWN_ACTIONS.START);
    } else if (onCountdown.status === COUNTDOWN_ACTIONS.START
      || onCountdown.status === COUNTDOWN_ACTIONS.CONTINUE) {
      dispatch(COUNTDOWN_ACTIONS.PAUSE);
    } else {
      dispatch(COUNTDOWN_ACTIONS.CONTINUE);
    }
  };

  useEffect(() => {
    if (onCountdown.status === COUNTDOWN_ACTIONS.START) {
      countdownAnimation.current = gsap.to(countdownTime, {
        sec: 0,
        ease: 'none',
        duration: getTotalSec(cardTime),
        onUpdate: () => {
          setTime(getMinSecFormat(countdownTime));
        },
      });
    }
    if (onCountdown.status === COUNTDOWN_ACTIONS.PAUSE) countdownAnimation.current.pause();
    if (onCountdown.status === COUNTDOWN_ACTIONS.CONTINUE) countdownAnimation.current.play();
  }, [onCountdown]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Pomotimer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Timer time={time} />
        <Cards />
        <button
          onClick={handlerOnTimer}
          className={styles.start_timer}
          type="button"
          style={onCountdown ? { backgroundColor: getColor('yellow') } : {}}
        >
          {
            onCountdown.btnText
          }
        </button>
      </main>
    </div>
  );
}
