import { Timer } from '@components/Timer';
import Head from 'next/head';
import { Cards } from '../components/Cards';
import { Header } from '../components/Header';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pomotimer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Timer />
        <Cards />
      </main>
    </div>
  );
}
